# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Install Git
RUN apt-get update && \
    apt-get install -y git

# Clone the Git repository
RUN git clone https://github.com/Partha2064/Python-Project.git

# Set the working directory to the cloned repository
WORKDIR /app/your-repo

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make the script executable
RUN chmod +x main.py

# Run script.py when the container launches
CMD ["python", "main.py"]
